- .ackrc
- Dockerfile
- Makefile
- ui/Makefile
- ui/nuxt.config.ts
- ui/pages/index.vue
- ui/stores/gpts.ts
- ui/stores/runs.ts
- ui/stores/socket.ts
Build the UI with the node image in docker, and an Acornfile
> Docker UI build

- examples/hacker-news-headlines.gpt
Enable re-running by checking for the mongodb container and either starting it or running it.
> fix - update hacker-news-headlines.gpt

- pkg/builtin/builtin.go
This PR changes the Override param to be a string instead of a bool. This was causing issues for scripts using the download tool.
> fix: address issue with override param

- go.mod
- go.sum
- pkg/builtin/builtin.go
Add a new built-in tool called `sys.append` that appends content to a file instead of truncating it.
Resolves https://github.com/gptscript-ai/gptscript/issues/24
I think this could also be implemented in `sys.write` by adding an extra parameter to indicate that an append is desired. Interested to hear if folks think that's a better approach.
> Append sys.append builtin

- docs/docs/tools/system.md
- pkg/builtin/builtin.go
created a built in tool that stats a file and returns the size, mode and mod time.
> enhance - add sys.stat built in tool

- Makefile
- README.md
- docs/docs/01-overview.md
- docs/docs/02-getting-started.md
- docs/docs/100-tools/01-using.md
- docs/docs/100-tools/02-authoring.md
- docs/docs/100-tools/03-offerings/01-image-generation.md
- docs/docs/100-tools/03-offerings/02-system.md
- docs/docs/100-tools/03-offerings/_category_.json
- docs/docs/100-tools/100-tools.md
- docs/docs/100-tools/_category_.json
- docs/docs/101-cookbook/_category_.json
- docs/docs/101-cookbook/image-generator.md
- docs/docs/tools/_category_.json
- docs/docusaurus.config.js
- docs/package.json
- scripts/gen-docs.gpt
First pass at some documentation around what tools are, how they work, and how you can make them. This also include some restructuring to make content flow more naturally.
To test this out, run `make serve-docs`.
At the time of creating this PR, the packaging format for external tools (as we want it to look) has not been implemented. This PR reflects the current state of things.
> feat: refactor docs and add content around tools and authoring

- .gitignore
These are going to start showing up in the examples. If you run the
recipegenerator example, you would see these as changes.
> Ignore common node and python files

- .gitignore
- README.md
- go.mod
- go.sum
- pkg/openai/client.go
#43 
Add a configurable env variable to set the azure deployment name to be used in lieu of the model name. Migrate away from using the snapshotted fork of `go-openai`, and add a hack for passing temperature.
> enhance: add support for azure deployment name mapping

- pkg/engine/cmd.go
- pkg/engine/http.go
- pkg/runner/log.go
- pkg/runner/runner.go
- pkg/tests/testdata/TestCwd/call3.golden
- pkg/tests/testdata/TestCwd/subtool/test.gpt
- pkg/tests/testdata/TestCwd/test.gpt
require tools use GPTSCRIPT_TOOL_DIR,
> Don't set the working dir of tools

- README.md
- docs/docs/01-overview.md
- docs/docs/100-tools/100-tools.md
For #48
Quick PR to improve the "copy" experience for our examples. This PR just separates examples commands from their output.
> docs: separate shell command from output in examples

- docs/README-USECASES.md
This PR adds use case doc for browse tool. It mostly redirect user to browser tool repo because all the dependencies are there.
> Add browser tool usecase doc

- main.go
- pkg/builtin/builtin.go
- pkg/loader/github/github.go
- pkg/loader/loader.go
- pkg/loader/url.go
- pkg/loader/vcs/init.go
- pkg/monitor/display.go
- pkg/server/server.go
- pkg/system/prompt.go
- pkg/types/tool.go
- **Add github metadata to internal data structures**
- **Print if it's a file or directory in stat call**
- **Print "No files found" in sys.find so LLM can handle empty case better**
> Add github metadata to internal data structures

- .gitignore
Add the releases directory to the .gitignore to prevent runtime/debug
from detecting a modified source tree when built via goreleaser. Before
this change, binaries built from tagged releases would return incorrect
version info with a '-dirty' suffix.
> chore: add releases to gitignore

- docs/docs/100-tools/03-offerings/02-image-generation.md
- examples/story-book/README.md
Updating the doc's site installation guide as well as clarifying some things with the story-book example's installation steps.
> docs: clarify details about installing the image-generation tool

- pkg/runner/runner.go
A previous attempt that uses time.Unix() as state file could cause conflicts, because there could be multiple calls happening at the same second when tools are invoked. Changing this to MilliSeconds should work.
> Fix: use milliseconds to record state file

- examples/story-book/README.md
This clarifies how a user can run the story-book a second time. We opted to not delete the `pages` directory in the script itself with concerns of UX.
> docs: update story-book readme to have a reset step

- .gitignore
- README.md
- docs/docs/02-getting-started.md
- pkg/openai/client.go
#43 #104 #78 
Add generic model mapping function for Azure use case. This will require the user to input a default model that is supported by Azure OpenAI, but will provide the least hacky solution, while also being future proof.
Just to note here so it's more easily readable for people who don't want to dive into the docs changes to understand the fix, to invoke you should set the default model to something supported by Azure OpenAI. If you are unsure what models are supported, you can find them by configuring the environment variables and running `gptscript --list-models`. Select one and pass it when invoking the script with the `--default-model` argument.
> fix: generic azure model support

- pkg/builtin/builtin.go
This will also add a `/` to the end of the names of directories, to indicate that they are directories and not normal files.
> fix: sys.find: stop ignoring directories

- pkg/openai/client.go
Correct the index used in a comparison that determines how internal
messages types are converted into their OpenAI equivalents.
Fixes https://github.com/gptscript-ai/gptscript/issues/135
> fix: compare role against next message in conversion conditional

- examples/car-notifier/Dockerfile
- examples/car-notifier/README.md
- examples/car-notifier/car-notifier.gpt
The README provides all the necessary info.
> docs: add car-notifier example

- go.mod
- go.sum
We have been seeing panic happening in our html2text tool which use tablewriter.
It turns out that there is a upstream bug https://github.com/olekukonko/tablewriter/pull/215.
Updating the library to the latest version should fix the issue.
Issue: https://acorn-io.slack.com/archives/C03FU91U4SX/p1710197266399329
> Fix: update tablewriter library to avoid panic

- pkg/repos/get.go
- pkg/repos/runtimes/golang/golang.go
When reference a tool in a subDir, for example
```
tools: github.com/gptscript-ai/search/duckduckgo, sys.http.html2text?
summarize nba standings for last season. Search using DuckDuckGo. Feel free to get the contents
of the returned URLs in order to get more information. Provide as much detail as you can.
```
The runtime is being called at the root level, not the subPath. Normally the file(main.go) will live in the same directory as tool.gpt, so runtime will fail. It probably makes more sense to assume all the files are living in the same directory within the subDir that it is referencing to.
Also, in go runtime, building in subDir will fail because of missing git VCS info. Adding `-buildvcs=false` should fix that.
> Fix: Use subPath as root dir when invoking runtime

- docs/README-USECASES.md
This PR adds new csv example and rework web browser to link existing example in browser repo.
> Chore: Add csv examples, rework web browser usecase

- pkg/repos/get.go
This was causing a bug where the first time you run a tool that comes from a multi-tool repo (such as gptscript-ai/search), it would work, but if you ever try to run any other tools from the same repo, they would not work. This is because the "done file" was being created in the wrong location (at the root of the repo, instead of at the location of the tool itself). This fixes that.
> fix: create done file in the right place

- pkg/cli/gptscript.go
New arguments -C and --chdir are added to control the working
directory of GPTScript.
> feat: Add -C to change cwd of GPTScript process

- pkg/system/prompt.go
Tested with all my browser examples by removing the manual instruction, seems to work well.
> Fix: add additional prompt to perform task one by one.

- pkg/builtin/builtin.go
Allow location to be a directory and then create temp filename for path.
Also attempt to make the final temp filename have the same extension as
the URL.
> feat: sys.download path enhancements

- pkg/parser/parser.go
I often forget what is the right parameter for json response so just
add more synonyms, json, json output, and json format.
> feat: add more synonyms for json response

- go.mod
- pkg/cli/gptscript.go
- pkg/types/completion.go
related to #13
When scanning through the output of gptscript, I am usually most interested in finding the tool calls. I figured that making the tool names green would make it easier.
We could easily add more colors to the output as well, but I wasn't really sure what else to do.
Here's an example of what it looks like:
> enhance: add green color to tool call names

- pkg/loader/loader.go
Using the --assemble flag will output the contents that can be read again by gptscript to construct a tool without going through all the steps again. This doesn't detect built-in tools, and will, instead, try to run the built-in tools like they are commands.
This change will detect the built-in tools to ensure they are run correctly.
> fix: detect built-in tools when loading from assemble output

- pkg/cli/gptscript.go
- pkg/gptscript/gptscript.go
- pkg/llm/registry.go
- pkg/openai/client.go
- pkg/remote/remote.go
You can now list models for a specific model provider by passing the
model provider name as an argument to --list-models
> feat: Add gptscript --list-models [PROVIDER]

- pkg/loader/loader_test.go
- pkg/parser/parser.go
Trim the optional leading whitespace from descriptions when parsing
arguments to prevent them from showing up in the chat completion function
definitions produced by gptscript.
> fix: trim leading whitespace from arg descriptions

- docs/docs/03-tools/03-openapi.md
- pkg/engine/openapi.go
- pkg/loader/openapi.go
This adds support for security schemes in the OpenAPI feature.
> enhance: openapi: add support for authentication

- pkg/loader/loader.go
- pkg/loader/openapi.go
These are fixes to various problems that Darren found with OpenAPI support. I annotated this PR to explain a bit about each substantial change.
> fix: various fixes for openapi support

- pkg/builtin/builtin.go
- pkg/cli/eval.go
- pkg/cli/gptscript.go
- pkg/engine/daemon.go
- pkg/runner/runner.go
- **feat: add sys.ls**
- **change: add hidden daemon and ports options**
> feat: add sys.ls

- pkg/engine/openapi.go
- pkg/loader/openapi.go
Two small fixes that I would like to get in before the next release:
1. Cap the tool description at 1024 characters so that OpenAI doesn't get mad.
2. Check for the bearer token for the server even if no security schemes are defined.
> fix: openapi: description length and default bearer auth

- pkg/engine/cmd.go
- pkg/engine/daemon.go
- pkg/repos/runtimes/golang/golang.go
This PR fixed some bugs around packaging and invoking golang runtime in windows.
> Fix: fix golang packaging in windows

- docs/docs/03-tools/03-openapi.md
Just a little docs change to make this example runnable.
> docs: fix OpenAPI petstore example

- pkg/server/server.go
These functions were mistakenly removed, so this change just adds them back.
> chore: add context functions for passing ids

- docs/docs/03-tools/04-credentials.md
- examples/car-notifier/README.md
- examples/hamlet-summarizer/README.md
Also added a bit of info about WinCred to the credential tool docs.
> docs: replace --cache=false with --disable-cache

- pkg/credentials/store.go
for #237
For some reason, when you get the auth back from the file credsStore, it doesn't have the server address set on it. We already know the server address, since it is basically the "key" which we use to look it up. So now we just set it if it's unset.
> fix: credentials: set server address on auth if it isn't set

- pkg/runner/runner.go
for #240
There was a problem where sometimes credential tools without `github.com` at the front of their name were having their credentials stored anyway. This change also skips the credential lookup for non-GitHub tools, since we aren't going to store the credentials for those anyway.
> fix: credentials: don't store creds for local credential tools

- pkg/parser/parser.go
- pkg/parser/parser_test.go
If a text node startwith with !word where word is any \w+ word the entire node is skipped until --- is found.
> feat: Add parser skip feature

- go.mod
- pkg/cli/gptscript.go
> fix: credentials: hide unneeded global flags

- pkg/remote/remote.go
I'm not sure why you set it as "\<unset\>" here, can you please explain?
> feat: warn when expected API key is missing

- pkg/loader/github/github.go
This PR allows an user to set a Github access/bearer token to authenticate against the Github API. Increases the request limit from [60](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users) to [5000](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users) requests per hour. When playing around with shim providers I reached the limit relatively fast. For me it was not even going away after several hours  - adding an auth token fixed it. 
Avoids this error: 
`HEAD: 403 Forbidden {"message":"API rate limit exceeded for 37.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. …
> Add option to set github auth token

- pkg/runner/runner.go
We were seeing cases where two credential tools could be run at the same time, causing weird issues in the terminal when `sys.prompt` was called. This fixes that.
for #250
> fix: credentials: do not prompt the user multiple times at once

- pkg/runner/runner.go
> fix: do not store empty credentials

- docs/docs/03-tools/04-credentials.md
- pkg/cli/credential.go
- pkg/cli/gptscript.go
- pkg/runner/credentials.go
- pkg/runner/runner.go
This adds the ability to override credentials with command line arguments or environment variables. See the docs in the PR for more information.
> enhance: add credential overrides

- pkg/cli/gptscript.go
- pkg/monitor/display.go
- pkg/monitor/fd.go
This change adds the ability to stream events to a file descriptor/handle, a file, or a named pipe.
> feat: add event streaming

- pkg/builtin/builtin.go
- pkg/context/context.go
- pkg/engine/cmd.go
- pkg/engine/engine.go
- pkg/runner/runner.go
for #256
One of the goals of the credentials framework was to block output to the terminal while running `sys.prompt`, since it prompts the user directly in the terminal. I originally implemented this by storing the Monitor into the Context and then pulling it out of the Context and running its `Pause` function in the implementation of `sys.prompt`. However, this does not work, as credential tools pretty much always have to call `sys.prompt` with a new gptscript subprocess.
This new implementation instead stores the Pause function inside of the context and calls it within the Engine code prior to running a credential tool. This way, the Monitor is paused in the correct process.
> fix: credentials: block output while running credential tools

- .gitignore
- .goreleaser.yml
- scripts/copy-cred-helper.sh
- scripts/download-cred-helpers.sh
This should be the last step for packaging the GPTScript credential helpers, which are small CLI programs (forked from the docker-credential-helpers repo) that gptscript uses to interact with OS keystores. The source for this is at github.com/gptscript-ai/gptscript-credential-helpers
I recently revamped and cleaned up the credential helper repo and created its first GitHub release, v0.1.0. I also combined the amd64 and arm64 darwin binaries into a single universal binary using github.com/g-linville/makefat, my fork of the tool github.com/randall77/makefat. (We can move this fork to gptscript-ai if we want. I basically just added CI and a goreleaser config for it, and set up reproducible builds.)
These changes add hooks to the goreleaser file to download the compiled binaries for …
> chore: include gptscript-credential-helpers in packaging

- docs/docs/08-sdks.md
The examples and documentation is limited because the READMEs in the individual repos contain the more thorough documentation. Links to the individual repos are included throughout.
> chore: add short documentation for the SDKs

- pkg/chat/chat.go
If you have a file with only "chat: true" and nothing else running it
from the CLI would result in an error.
> bug: fix simple "hello world" chat use case

- pkg/engine/cmd.go
- pkg/tests/runner_test.go
- pkg/tests/testdata/TestShlex/test.gpt
This reverts commit b5e053ca9253f95dc083bdcc128e37b0d25c9f47.
> Revert "bug: expand interpreter args to multiple arguments"

- examples/nodejs-imagegen/server.js
- examples/time.gpt
Fix time.gpt example to add more guidance to timezone arg's description to make it work more reliably with other provider models.
Fix nodejs-imagegen example to use the dalle-image-generation repo.
> Fix time.gpt example to add more guidance to arg description and nodejs-imagegen example to use the dalle-image-generation repo.

- pkg/types/tool.go
If instructions are not printed last, then anything printed after the instruction is parsed as instructions. For example:
```
Hello, how are you?
Chat: true
```
would not be parsed as a chat tool.
This change will ensure that things that are fmt-ed will also be parsed the same way.
> fix: print instructions last when fmt-ing

- pkg/engine/openapi.go
Some apis don't require content in the request body. If that was the case the current implementation doesn't send a header or the empty body.
This change makes it so the empty json and string bodies and headers are sent.
note: need to discuss if there is a scenario for empty multipart form data.
> fix: handle empty request bodies

- pkg/engine/engine.go
- pkg/runner/runner.go
added just enough checks to prevent some panics on invalid chat state inputs encountered while investigating https://github.com/gptscript-ai/gptscript/issues/311
> chore: prevent panics on invalid state input

- pkg/loader/openapi.go
The random assignment causes issues when gptscript looks up by id which is tied to the operation number.
The bug would show up with could not find file <something:operationNum> causing the app to crash. It might be a symptom of chat mode, because the openapi tools are parsed on each turn.
> fix: openapi tools received random operationNums

- pkg/loader/loader.go
- pkg/loader/loader_test.go
- pkg/remote/remote.go
- pkg/types/toolname.go
- pkg/types/toolname_test.go
Uses the toolname before the from otherwise it was using the filename and appending numbers losing context.
> fix: tool names should be used instead of filename

- pkg/chat/chat.go
- pkg/loader/github/github.go
- pkg/parser/parser.go
- pkg/tests/testdata/TestCase/call1.golden
- pkg/tests/testdata/TestCase2/call1.golden
When importing things from github or other case sensitive location the previous functionality would lowercase everything causing clones from VCS to fail.
This fix removes the calls to lowercase tools and contexts along with the other places they occur.
> fix: do not lowercase all items in tool(like) lists

- docs/docs/03-tools/05-context.md
> Chore: Add documentation for context

- go.mod
- go.sum
- pkg/loader/loader.go
- pkg/loader/loader_test.go
- pkg/loader/testdata/openapi_v2.json
- pkg/loader/testdata/openapi_v2.yaml
- pkg/loader/testdata/openapi_v3.yaml
Support OpenAPI v2 spec for tools by converting them up to v3 and re-using the existing v3 logic.
Is Yaml? -> Transform to JSON -> Is JSON? -> Unmarshal to OpenAPI v2 spec -> convert to OpenAPI v3 spec -> treat with existing v3 logic.
> add: OpenAPI v2 tools support

- docs/docs/04-alternative-model-providers.md
only merge after https://github.com/gptscript-ai/anthropic-provider/pull/5 is done
> chore: update docs to reflect changes to anthropic provider

- examples/sentiments.gpt
Re-engineer the `sentiments.gpt` example tool body prompt wording so that it works with `claude-3-opus` and `gemini-1.5`.
- The existing prompt is useful in identifying the shortcomings of these LLMs, so it may be useful to keep around in some capacity.
- `claude-3-opus` is interesting because it, along with `gpt-4-turbo` and `gpt-4o`, are capable of inferring the necessary sequence of chained tool calls and come to the correct result with a prompt as basic as `Get the sentiments of the tweet at ${url}.`. For that same basic prompt, `gemini-1.5` fails to chain functions at all and just immediately calls `sentiments` with hallucinated text.
> docs: improve sentiments example model compatibility

- go.mod
- go.sum
- pkg/auth/auth.go
- pkg/builtin/builtin.go
- pkg/cli/eval.go
- pkg/cli/gptscript.go
- pkg/cli/sdk_server.go
- pkg/context/context.go
- pkg/engine/daemon.go
- pkg/engine/engine.go
- pkg/engine/http.go
- pkg/gptscript/gptscript.go
- pkg/loader/loader.go
- pkg/loader/openapi.go
- pkg/monitor/display.go
- pkg/monitor/fd.go
- pkg/mvl/log.go
- pkg/parser/parser_test.go
- pkg/runner/runner.go
- pkg/sdkserver/confirm.go
- pkg/sdkserver/middleware.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/run.go
- pkg/sdkserver/server.go
- pkg/sdkserver/types.go
- pkg/server/server.go
- pkg/types/tool.go
This server will be used in the SDKs for running gptscripts.
> feat: add a new SDK server

- pkg/monitor/fd.go
When running gptscript with providers and --events-stream-to flag, the file passed to --events-stream-to would be closed after the provider was setup. This is an error because the file should remain open for the duration of the script run.
This change will ensure that the file is only closed when the script is complete.
Additionally, this change introduces 0644 permissions when creating a file passed to --events-stream-to.
> fix: ensure fd monitor file is closed at end of the script run

- pkg/monitor/fd.go
When chatting, the file passed to --events-stream-to is closed and the events for chat messages aren't appended. This change will reopen the file when necessary and continue streaming events to the file.
> fix: make --events-stream-to work with chat

- pkg/cli/eval.go
- pkg/cli/gptscript.go
- pkg/env/env.go
The chat UI option is sugar to launch the chat-builder tool. If the user enables the chat-ui option, then the appropriate setup is done to launch the chat-builder UI tool for the user. If the a file is provided, then the UI should launch to the "run" UI and the user can chat with the provided tool. If no file is provided, then the "browse" UI is opened and the user can decide what to do.
The most important secondary option is the --chdir option. If the user provides a file, then the current directory will be set to the directory where that file exists. If the user provides the --chdir option, then the file path should be absolute or relative to this chdir.
> feat: add chat-ui option

- .goreleaser.yml
Update goreleaser homebrew tap config to generate shell completions for `gptscript` on install.
> chore: generate shell completions on brew install

- pkg/loader/openapi.go
According to the spec readOnly fields SHOULD NOT be sent in the request, but maybe present in the response. The LLM has made several errors making calls when these fields are present by including the readOnly fields in the request and getting HTTP 422's.
This change loops through the args, and drops readOnly fields from the requestBodyContent arg on the tool.
> fix: do not add readOnly fields to the requestBody

- pkg/engine/cmd.go
Some commands, like powershell, require the files it runs to end with a particular extension. This change sets up this requirement with the ability to add more later.
> fix: add ability to set required extensions for certain commands

- Makefile
The target is broken - it is calling a gptscript that was deleted awhile
ago. We probably do want a new version of gen-docs, but this isn't it.
So, I'm deleting it for now.
> Remove gen-docs make target

- pkg/sdkserver/prompt.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/server.go
If the prompt token is not present in the environment, then gptscript will hijack the prompt handling. This change adds a prompt token to the sdkserver to avoid this hijacking.
> fix: add prompt token to sdkserver

- go.mod
- go.sum
- pkg/cli/gptscript.go
- pkg/mvl/log.go
- pkg/openai/client.go
The tui supports disable-cache, cache-dir, and sub-tool now.
> chore: default to tui, support more flags

- pkg/cli/gptscript.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/server.go
- pkg/server/server.go
Instead of using a default port of 9090, this change will set the port for the various servers to a random available port.
> fix: use random available port by default

- go.mod
- go.sum
- pkg/chat/chat.go
- pkg/cli/eval.go
- pkg/cli/gptscript.go
- pkg/runner/runner.go
This also makes is so that if you want "stateless" chat through the CLI
you have to do --save-chate-state-file stdout
> chore: add --save-chat-state-file

- pkg/gptscript/gptscript.go
If the URL and token environment variable are set outside gptscript, then the credential prompting tool needs those variables. In this case, the extraEnv is nil and doesn't allow prompting to work.
Additionally, the credential context default is needed when completing the opts for the SDK server.
> fix: use entire env for credential prompting

- go.mod
- go.sum
- pkg/cli/gptscript.go
- pkg/gptscript/gptscript.go
Passing these extra environment variables allows the tui to know that it doesn't need to handle prompting the user, and gptscript will handle it.
> fix: pass ExtraEnv to tui

- pkg/cli/gptscript.go
- pkg/gptscript/gptscript.go
- pkg/prompt/server.go
- pkg/sdkserver/routes.go
When running the UI all prompts except the first prompt for an OpenAI key should go through the UI. Therefore, the prompt environment variables shouldn't go to the UI tool.
> fix: clear prompt env vars when running the UI

- .github/workflows/test.yaml
- .golangci.yml
- Makefile
- docs/docs/03-tools/04-credentials.md
- pkg/parser/parser.go
- pkg/runner/runner.go
- pkg/types/credential_test.go
- pkg/types/tool.go
- test.gpt
This adds support for aliases and arguments in credential tools. Read the docs changes in the PR to find out how it works.
> enhance: add support for args and aliases to credential tools

- README.md
- docs/docs/01-overview.md
> Docs: Reintroduce install.sh

- go.mod
- go.sum
- pkg/loader/openapi.go
- pkg/parser/parser.go
- pkg/system/prompt.go
- pkg/types/jsonschema.go
Bumped our openapi dependency while writing the smoke test framework and noticed there's a breaking change. Since we need to do this eventually, I figured I should get this out of the way sooner.
> chore: bump kin-openapi dependency

- pkg/types/toolname.go
The tool names have to be unique, so if two tools are added with the same name, they have a 0 appended to them. In this case we got into an infinite loop because toolName was incremented not the variable under test. So we ended up in an infite loop.
> fix: infinite loop while creating gptscript toolset based on name

- pkg/daemon/daemon.go
- pkg/server/server.go
Windows won't allow the forked command to start while stdin is being held open. This means that daemons won't work on Windows. This fix bypasses this by not providing os.Stdin to the forked command.
> fix: allow daemons on Windows

- pkg/cli/parse.go
- pkg/loader/url.go
This PR adds support for remote file parsing. This will mainly be a nice feature for the SDKs as consumers of them can now parse file remotely prior to executing them. Namely, the UI will use this functionality.
This is done by exporting `loader.ContentFromURL` as a new public function. The `input` package then uses `loader.ContentFromURL` in a new `input.FromURL` function. This allows all of the same loading logic to apply that GPTScript runs do while also leveraging the same cache that they do. Finally, the `parse` subcommand calls `input.FromURL` if a file load fails.
> feat: add support for remote file parsing

- pkg/engine/cmd.go
Binding os.Stdin, which will not be closed in gptscript, causes issues with Windows because the subcommand will wait for stdin to be closed before launching. Since we are not using stdin with subcommands, this binding can safely be removed.
> fix: stop binding os.Stdin to sub commands

- pkg/cli/gptscript.go
- pkg/system/bin.go
When starting gptscript in the various modes (CLI, UI, server, etc), the same binary should be used for the whole stack via the GPTSCRIPT_BIN environment variable. This change does exactly that.
> chore: ensure gptscript stack uses the same binary

- pkg/cli/parse.go
- pkg/input/input.go
- pkg/sdkserver/routes.go
Add the ability to parse remote scripts in the sdkserver.
To test this, you can do the following after pulling the branch down locally:
```sh
go run main.go --debug --listen-address 127.0.0.1:9090 sdkserver
```
and in a separate tab:
```sh
curl http://localhost:9090/parse -d '{"file":"github.com/gptscript-ai/cli-demo"}'
```
> feat: add sdkserver support for remote file parsing

- docs/docs/02-credentials.md
- docs/docs/03-tools/04-credential-tools.md
- pkg/cli/credential.go
- pkg/cli/credential_delete.go
- pkg/config/cliconfig.go
- pkg/credentials/noop.go
- pkg/credentials/store.go
- pkg/credentials/util.go
- pkg/engine/engine.go
- pkg/gptscript/gptscript.go
- pkg/openai/client.go
- pkg/prompt/credential.go
- pkg/remote/remote.go
- pkg/repos/get.go
- pkg/repos/runtimes/golang/golang.go
- pkg/runner/runner.go
- pkg/tests/tester/runner.go
This PR adds functionality to GPTScript to automatically clone and build the GPTScript credential helpers. I also expanded the information in the docs to explain each of the available helpers. I have tested this on Windows, macOS, and Linux, but I would like for at least one of the reviewers to test it on his system as well.
> enhance: automatically set up credential helpers

- pkg/gptscript/gptscript.go
- pkg/openai/client.go
- pkg/runner/runner.go
A previous change completed all the options, including setting defaults when running gptscripts. This caused issues with "no-op" defaults being set before they should have. This change will only complete the CLI args and wait for the remaining defaults to be set until all CLI args have be completed.
> fix: only complete CLI args when running gptscript

- pkg/cli/gptscript.go
This is necessary in combination with a change to the UI tool that will allow URLs to be passed through to the `run` routes `file` query param.
> fix: support passing along URLs to the UI

- pkg/cli/credential.go
- pkg/cli/credential_show.go
This adds a new command to show the environment variables that are stored in a credential.
> enhance: add credential show command

- pkg/engine/openapi.go
- pkg/loader/openapi.go
- pkg/types/tool.go
- pkg/types/tool_test.go
This is a relatively simple change that just adds a `Credential:` line or two to each tool generated for an OpenAPI definition, if there is some supported security scheme for the particular operation (i.e. API key, HTTP bearer token, HTTP basic auth).
This works seamlessly with existing OpenAPI tool examples such as the DigitalOcean agent.
> enhance: automatically use the generic credential tool for OpenAPI

- pkg/runner/monitor.go
- pkg/runner/runner.go
for #483
~~This creates a little wrapper type around the monitor, to be used only for credential calls, so that we do not print the plaintext output to the console.~~
Update: this instead excludes the output of credential tools from the CallFinish Event entirely, so the Monitor never has a chance to see it.
> fix: redact output of credential tools

- pkg/cli/gptscript.go
- pkg/loader/loader.go
- pkg/types/tool.go
Use a shared map instance so that memory doesn't blow up because the
tool mapping is implicitly n*n.
> bug: large openapi schemas require n^2 memory

- .github/workflows/smoke.yaml
The current name is "test" which conflicts with the existing "test"
workflow and causes the GitHub UI to get confused.
> chore: fix smoke workflow name

- .github/workflows/validate-docs.yaml
- docs/docs/04-command-line-reference/gptscript.md
- docs/docs/04-command-line-reference/gptscript_eval.md
- docs/docs/04-command-line-reference/gptscript_fmt.md
- docs/docs/04-command-line-reference/gptscript_parse.md
- docs/docs/09-faqs.md
> docs: add FAQ about caching

- docs/docs/09-faqs.md
> docs: add FAQ for workspace

- pkg/tests/judge/judge.go
- pkg/tests/smoke/smoke_test.go
- pkg/tests/smoke/testdata/Bob/claude-3-opus-20240229-expected.json
- pkg/tests/smoke/testdata/Bob/gpt-4-turbo-2024-04-09-expected.json
- pkg/tests/smoke/testdata/Bob/gpt-4o-2024-05-13-expected.json
- pkg/tests/smoke/testdata/Bob/mistral-large-2402-expected.json
- pkg/tests/smoke/testdata/Bob/test.gpt
- pkg/tests/smoke/testdata/BobAsShell/claude-3-opus-20240229-expected.json
- pkg/tests/smoke/testdata/BobAsShell/gpt-4-turbo-2024-04-09-expected.json
- pkg/tests/smoke/testdata/BobAsShell/gpt-4o-2024-05-13-expected.json
- pkg/tests/smoke/testdata/BobAsShell/mistral-large-2402-expected.json
- pkg/tests/smoke/testdata/BobAsShell/test.gpt
Perform some prompt engineering on the smoke test judge and test cases
to make result comparison more reliable. This will stop the smoke tests from
flaking.
Note: Reran this with `-count=10` for each model locally and didn't get any flakes.
> fix: smoke test flakes

- .github/workflows/smoke.yaml
The default GitHub workflow token isn't privileged enough to check org membership for PR authors. This prevents smoke tests for running automatically for org members. To fix this, switch to a PAT with the correct privileges for this check.
Reminder: This change won't affect the runs for this PR since the workflow files are always pulled from the base branch.
> fix: auto run smoke tests for members

- pkg/cli/credential.go
- pkg/credentials/credential.go
- pkg/runner/runner.go
This adds support for expiration and refresh tokens to the credential framework. All of these changes are backwards compatible with existing credentials, though new credentials will be stored in a slightly different format.
Notable changes:
- An expiration time for the credential will be saved if the cred tool provides that field. Once the credential is expired, the next time it is requested, the credential tool will be run again.
- A refresh token for the credential will be saved if the cred tool provides that field. This is useful in certain OAuth situations for requesting a new token without user interaction.
- `gptscript cred` output looks a little nicer and displays more information.
> enhance: update credentials framework for OAuth support

- docs/docs/03-tools/02-authoring.md
> docs: explain how to set args from the command line

- pkg/loader/url.go
This function was automatically attaching `agent.gpt` or `tool.gpt` to the end of URLs that didn't already contain a `.` in their last path element. This broke use cases like `tools: https://petstore.gptscript-demos.ai/openapi`, because it totally ignored the main URL and tried to look for those two tool files instead. This fixes that problem.
for #537
> fix: get remote file before appending default file names

- pkg/gptscript/gptscript.go
Previously, we were only building the credential helper right before handling credential tools. But the helper is also needed for looking up model provider keys like `sys.openai`. This leads to crashes on new installations. For now, the solution is to just always build the credential helper. Once Darren is back, we can figure out how to do this in a better way if he is dissatisfied with it.
> fix: always build credential helper

- pkg/engine/engine.go
- pkg/monitor/display.go
- pkg/monitor/fd.go
- pkg/runner/monitor.go
- pkg/runner/runner.go
- pkg/sdkserver/monitor.go
The sdkserver is sending multiple run start and finish events for provider
tools which causes stream processing to terminate prematurely.
To fix this, only send start and finish events when the tool category isn't set.
> fix: send only one run start/finish event from sdkserver

- pkg/cli/credential.go
- pkg/cli/credential_delete.go
- pkg/cli/credential_show.go
- pkg/cli/eval.go
- pkg/cli/gptscript.go
- pkg/credentials/noop.go
- pkg/credentials/store.go
- pkg/gptscript/gptscript.go
- pkg/openai/client.go
- pkg/prompt/credential.go
- pkg/remote/remote.go
- pkg/runner/runner.go
- pkg/sdkserver/run.go
- pkg/sdkserver/server.go
Instead of building the credential helpers on startup, this change builds them when they are needed. This speeds up start time for the SDK.
> feat: build credential helpers just in time

- pkg/builtin/builtin.go
To add environment variables to a sys.exec call, the user can populate a gptscript.env file with a list of environment variables per line in the format:
```
FOO=bar
```
This file can be precreated or modified by gptscripts.
> enhance: add support for gptscript.env file in workspace

- go.mod
- go.sum
- pkg/openai/client.go
- pkg/system/prompt.go
- pkg/tests/runner_test.go
- pkg/tests/testdata/TestAgents/call1.golden
- pkg/tests/testdata/TestAgents/call2.golden
- pkg/tests/testdata/TestAgents/call3.golden
- pkg/tests/testdata/TestAgents/step1.golden
- pkg/tests/testdata/TestAsterick/call1.golden
- pkg/tests/testdata/TestContextSubChat/call1.golden
- pkg/tests/testdata/TestContextSubChat/call4.golden
- pkg/tests/testdata/TestContextSubChat/call6.golden
- pkg/tests/testdata/TestContextSubChat/call9.golden
- pkg/tests/testdata/TestContextSubChat/step1.golden
- pkg/tests/testdata/TestContextSubChat/step3.golden
- pkg/tests/testdata/TestDualSubChat/call1.golden
- pkg/tests/testdata/TestDualSubChat/call7.golden
- pkg/tests/testdata/TestDualSubChat/step1.golden
- pkg/tests/testdata/TestDualSubChat/step2.golden
- pkg/tests/testdata/TestDualSubChat/step3.golden
- pkg/tests/testdata/TestExport/call1.golden
- pkg/tests/testdata/TestExport/call3.golden
- pkg/tests/testdata/TestExportContext/call1.golden
- pkg/tests/testdata/TestSubChat/call1.golden
- pkg/tests/testdata/TestSysContext/call1.golden
- pkg/tests/testdata/TestSysContext/step1.golden
- pkg/tests/testdata/TestToolAs/call1.golden
This is probably the wrong thing to do. We need to differientiate
between empty args and no args. If a tool has no params defined
then {} should be dropped. Right now this logic is in the wrong spot
to do that so we just go back to the old behavior of just always dropping
{} which will cause a problem for tools that would expect an empty object.
> bug: go back to old behavior of dropping {} for tools

- pkg/credentials/credential.go
- pkg/credentials/helper.go
- pkg/remote/remote.go
- pkg/types/tool.go
for #509 
Details in comments.
> fix: don't prompt for creds for local models

- pkg/sdkserver/routes.go
- pkg/sdkserver/types.go
Expose the `credentialOverride` field in the request payload for the run/eval sdkserver
endpoints. This will enable credential override support to be implemented by the SDKs.
Related issue: https://github.com/gptscript-ai/gptscript/issues/553
> enhance: plumb credential context into run/eval requests

- pkg/cli/gptscript.go
Use the matching tagged version of the UI tool for release builds when
the `--ui` option is given. Use main for all other builds of gptscript.
> chore: pull ui tool with matching release tag

- pkg/credentials/util.go
- pkg/repos/get.go
We used to check the GH repo information for the credential helpers repo every time a cred store operation (get, list, etc.) was called. This is way too many lookups and hits the rate limit. This PR adds a file to hold a timestamp for the last time the repo was checked, and only check again if at least 24 hours have passed.
> fix: only check cred helper repo once per 24h

- pkg/types/tool.go
This requirement would probably cause us more problems than it's worth (like weird edge cases in tool generation for OpenAPI), so it's probably best that we just remove it.
> fix: remove requirement that cred aliases be alphanumeric

- pkg/gptscript/gptscript.go
Before this change, the environment variables would take precedence for setting the GPTSCRIPT_WORKSPACE_DIR. This is incorrect because gptscript should be solely responsible for setting these environment variables. Putting these environment variables at the end of the list ensures that they take precedence.
> fix: make the WorkspacePath take absolute precedence for setting env var

- pkg/repos/get.go
If the cache directory is gone, then, currently, writing the last-checked file fails. This change ensures that the directory exists before trying to write the file.
> fix: create the cache directory before writing last-checked file

- pkg/engine/openapi.go
When joining url paths, you sometimes end up with // or /./ in them. When interacting with some apis you get redirects, like a 308, that are not handled by the default client.
This just cleans it up in an effort to avoid.
> fix: join the server and url with url joinpath.

- .github/workflows/smoke.yaml
- pkg/loader/github/github.go
- pkg/loader/github/github_test.go
- pkg/loader/url.go
- pkg/repos/get.go
- pkg/tests/smoke/testdata/Bob/claude-3-opus-20240229-expected.json
- pkg/tests/smoke/testdata/BobAsShell/claude-3-opus-20240229-expected.json
With this change, we now use the GitHub token for VCS lookups when resolving tools. This can help avoid rate limits.
I also fix the Claude smoke test in this PR, but it runs the old version against this PR, which is why it is still failing.
> fix: use GH token for VCS lookups

- pkg/cli/gptscript.go
The credential subcommands throw a nil ptr exception due to a nil
credential override flag value. Prevent this by including the value when
hiding flags from credential subcommands.
@g-linville and I missed this in #596
> fix: option hiding in cred subcommands

- pkg/credentials/util.go
- pkg/repos/get.go
The `path.Dir` function was totally broken on Windows (I think it was returning an empty string or something). This fixes the problem
> fix: create cred helper dir properly on Windows

- pkg/cli/gptscript.go
Pass credential overrides to the UI by setting the UI tool's `GPTSCRIPT_SDKSERVER_CREDENTIAL_OVERRIDE` environment variable before running it.
> enhance: set sdk cred override env var for ui

- pkg/loader/loader_test.go
- pkg/loader/openapi.go
- pkg/loader/openapi_test.go
- pkg/loader/testdata/openapi/TestOpenAPIv2.golden
- pkg/loader/testdata/openapi/TestOpenAPIv3.golden
- pkg/loader/testdata/openapi/TestOpenAPIv3NoOperationIDs.golden
- pkg/loader/testdata/openapi_v3_no_operation_ids.yaml
> enhance: generate name for OpenAPI tools when operation ID is blank

- .github/workflows/smoke.yaml
- pkg/tests/smoke/testdata/Bob/mistral-large-2402-expected.json
- pkg/tests/smoke/testdata/BobAsShell/mistral-large-2402-expected.json
Use https://github.com/gptscript-ai/mistral-laplateforme-provider for mistral smoke tests instead of hitting the La Plateforme API directly.
> chore: use laplateforme provider for mistral smoke tests

- .github/workflows/integration.yaml
- Makefile
- integration/cred_test.go
- integration/helpers.go
We talked about adding a simple test to just run `gptscript cred`. Here is that test.
> enhance: add simple integration test

- pkg/daemon/daemon.go
We should try to send os.interupt to sys daemon process. This allows daemon process to be able to intercept and perform possible cleanup function.
It was causing an issue where in browser tool, when script is executed, the browser session is not closed.
> Fix: Try to send interupt to sys.daemon to allow cleanup

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- go.mod
There is a change in 1.22.5 that breaks sys.daemon on Windows. Fixing this version for now until we address this issue.
> chore: fix Go version to 1.22.4

- pkg/daemon/daemon.go
This reverts commit 1104843ccc7c571568756e8468d7607d546fb467.
Causing issue in other LLM provider, reverting.
> Revert "Fix: Try to send interupt to sys.daemon to allow cleanup"

- pkg/daemon/daemon.go
Reverts gptscript-ai/gptscript#611.
The providers will be updated to handle interrupts gracefully to accommodate this change.
See:
- https://github.com/gptscript-ai/mistral-laplateforme-provider/pull/1
- https://github.com/gptscript-ai/claude3-anthropic-provider/pull/7
- https://github.com/gptscript-ai/claude3-bedrock-provider/pull/1
- https://github.com/gptscript-ai/azure-other-provider/pull/3
- https://github.com/gptscript-ai/azure-openai-provider/pull/2
- https://github.com/gptscript-ai/gemini-aistudio-provider/pull/2
- https://github.com/gptscript-ai/gemini-aistudio-provider/pull/2
> Un-revert "Fix: Try to send interupt to sys.daemon to allow cleanup""

- .goreleaser.yml
- README.md
- docs/docs/01-overview.md
This means releases will get into homebrew-core when their automation detects we have released a new version. Looking at the last several releases, it looks like that takes ~2 hours after we cut our release.
> chore: remove references to tap in favor of homebrew-core

- examples/gptreview.gpt
Add GPTReview example for part 1 of the blog post.
> Add GPTReview Example

- pkg/loader/loader.go
- pkg/loader/url.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/run.go
- pkg/sdkserver/types.go
- **chore: add location option to loading scripts**
- **bug: fix relative references when defaulting files from dirs**
> chore: add location option to loading scripts

- pkg/cli/gptscript.go
Set the `UI_RUN_FILE` env var before starting the UI tool
when a run file is provided; e.g. `gptscript --ui <run-file.gpt>`. This
tells the UI to use the file's run page as the landing page on start.
Depends on https://github.com/gptscript-ai/ui/pull/30
> chore: set the run file env var when starting the ui

- integration/cred_test.go
- integration/helpers.go
- integration/scripts/credscopes.gpt
- pkg/parser/parser.go
- pkg/runner/runner.go
- pkg/types/tool.go
This adds a new tool parameter, `Share Credentials` (with several aliases), which is essentially the same thing as `Share Tools` but specifically for credential tools.
I also added a new integration test that tests credential "scopes" to make sure that in a tree of tools that define and share credentials, each tool only has access to credentials that it defines and credentials shared by its immediate children in the tree.
> enhance: share credential

- pkg/cli/sdk_server.go
- pkg/sdkserver/server.go
Additionally, this change includes a way to run the server embeddedly in another process that may use stdin.
> feat: improve SDK server start up

- examples/gptreview-ghaction/README.md
- examples/gptreview-ghaction/codereview.gpt
- examples/gptreview-ghaction/workflow.yaml
Adding example for GPTReview using GitHub Actions
> Add GPTReview With GitHub Example

- pkg/engine/engine.go
- pkg/tests/runner_test.go
- pkg/tests/testdata/TestMissingTool/call1-resp.golden
- pkg/tests/testdata/TestMissingTool/call2.golden
When the LLM tries to call a tool that doesn't exist, gptscript is supposed to give it an error message so that it can correct itself and keep working. But if the tool name that the LLM hallucinated is an invalid tool ID, then gptscript would crash. This change makes it so that we normalize the hallucinated tool name first and avoid crashing.
> fix: normalize LLM-hallucinated tool names

- docs/docs/09-faqs.md
Added workaround that can be done when gptscript execution results in github rate limit errors in FAQ section.
> Docs - Add faq for github rate limit

- .github/workflows/release.yaml
Since gptscript is on the homebrew autobump list, the formula can't be updated manually.
> chore: remove homebrew-release step

- examples/gptreview-jenkins/Jenkinsfile
- examples/gptreview-jenkins/README.md
- examples/gptreview-jenkins/codereview.gpt
Adding GPTReview with Jenkins example.
> Add GPTReview Jenkins example

- pkg/remote/remote.go
When using the default model provider flag, the default model will be
gpt-4o. However, when it is parsed, the expected format is 'gpt-4p from
my-model-provider'. When using a default model provider, the 'gpt-4o'
was being parsed and the model was set to the empty string.
After this change, if the model name is empty after parsing, then we
know that the model from the request doesn't have a 'from' in it and the
first part of the split reference should be used.
> fix: ensure default model is parsed when using default model provider

- docs/docs/02-examples/01-cli.md
- docs/docs/02-examples/02-api.md
- docs/docs/02-examples/04-local-files.md
- docs/docs/02-examples/05-workflow.md
- docs/docs/03-tools/02-authoring.md
I significantly modified the first two examples (GitHub CLI and DigitalOcean API) to make them single-agent, simplifying them quite a bit. I also improved the wording and formatting in the local files example, and the formatting in the automated workflow example.
I'm currently blocked by a particular bug, but once it is fixed I will submit a follow-up PR with a new multi-agent example that combines the GH CLI and DO API examples.
> docs: improve examples

- pkg/prompt/prompt.go
This essentially allows tools to "display" info to a user, even when using SDKs.
> feat: include fields in prompt only when there are fields

- docs/docs/03-tools/08-workspace.md
- docs/docs/03-tools/09-code-tool-guidelines.md
- docs/docs/03-tools/10-daemon.md
- docs/docs/09-faqs.md
- I moved the info about workspaces from the FAQ page to its own page.
- I added a page to provide additional guidelines about how to structure code-based tools in GitHub repos.
- I added a page about daemon tools.
- I added a section to the FAQ about saving and resuming chat state.
> docs: document more features

- pkg/parser/parser.go
- pkg/runner/runner.go
- pkg/tests/runner_test.go
- pkg/tests/testdata/TestToolRefAll/call1-resp.golden
- pkg/tests/testdata/TestToolRefAll/call1.golden
- pkg/tests/testdata/TestToolRefAll/test.gpt
- pkg/types/tool.go
- pkg/types/tool_test.go
This allows the tools field to reference tools, context tools, or agent
tools without using the context:, agent: fields.
> chore: add type field to tools

- docs/docs/03-tools/11-input-output-filters.md
I did not even know this feature existed until a couple days ago, lol.
> docs: input and output filters

- pkg/loader/loader.go
this fixes an issue seen at least in clio, with the ability to load external agents.
> fix: windows absolute path logic

- pkg/remote/remote.go
By not caching the client, gptscript is able to restart the provider daemon if it stops. If the daemon is still running, then there is little overhead because the daemon URL is cached and the tool will not be completely reprocessed.
The model to provider mapping is still cached so that the client can be recreated when necessary.
> feat: allow providers to be restarted if they stop

- pkg/engine/cmd.go
- pkg/engine/cmd_test.go
When reading the #! interpreter line variables in quotes "${FOO}" will
be evaluated and passed as a single argument to the command. Unquoted
variables like ${FOO} may result in multiple argument. For example,
if FOO="Hello World" that will result in two arguments "Hello" and
"World", where "${FOO}" will result in one argument "Hello World"
> bug: change quoting behavior

- pkg/openapi/run.go
This fixes an issue where there are multple entries in openapi auth schema that need to be added to query parameters. The current approach only adds the last one.
Found the bug when testing with trello openapi.
```
"securitySchemes": {
"APIKey": { "type": "apiKey", "in": "query", "name": "key" },
"APIToken": { "in": "query", "name": "token", "type": "apiKey" }
},
```
> Fix: Fix query not added if there are multple entries

- pkg/cli/gptscript.go
Pin the UI version to ensure `--ui` continues to work while we transition to a electron app based experience.
> chore: pin ui tool version to v0.9.4

- .github/workflows/release.yaml
The UI must be updated independently from now on for electron releases to work properly.
> chore: remove ui dispatch from release workflow

- pkg/engine/daemon.go
- pkg/remote/remote.go
A previous change stopped caching clients so that they would be restarted whenever needed. However, the running of the tool produces unwanted output if the provider is already running.
This change includes a way to tell whether the provider is running or needs to be restarted.
> fix: stop running tool for providers that are runnning

- pkg/types/tool.go
Looks like I was calling the wrong function before.
> fix: share credentials in context tools

- pkg/remote/remote.go
Apparently, this code path is exercised by listing models and not by using the provider with LLM calls.
> fix: address panic when listing models with default model provider

- pkg/loader/openapi.go
Panics in cases like:
```yml
requestBody:
required: true
content:
application/json: {}
``` 
- `gptscript --list-tools https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml`
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9d209e]
goroutine 1 [running]:
github.com/gptscript-ai/gptscript/pkg/loader.getOpenAPITools(0xc0000e1ef0, {0xc0001900a0, 0x4a}, {0xc0001900a0, 0x4a}, {0x0, 0x0})
github.com/gptscript-ai/gptscript/pkg/loader/openapi.go:212 +0x2b7e
...
```
> fix(openapi): don't panic on requestBody content mime without schema

- pkg/loader/openapi.go
When using an OpenAPI definition with multiple security infos that should be AND'd together (per https://docs.gptscript.ai/tools/openapi#1-security-schemes), the tools credential injection with only include 1 of the environment variables instead of all of them. The result is non-deterministic on which envvar will be included to do Go's behavior with slices.
This changes the behavior to include credential injections for all schemes declared in the 1st security info block in the api definition.
> fix: Append all credentials for OpenAPI security infos

- pkg/openapi/run.go
- pkg/types/toolstring.go
This PR does two things in the OpenAPI revamp:
- When the LLM provides arguments that do not match the JSONSchema, rather than exiting with an error, the validation errors are returned as a normal message to the LLM so that it can respond by trying again.
- The confirmation prompt shown to the user when running an OpenAPI operation under the OpenAPI revamp is improved to provide details about the specific operation and arguments.
> fix: openapi: return validation errors to the LLM; improve confirmation prompt

- pkg/builtin/builtin.go
- pkg/prompt/prompt.go
- pkg/sdkserver/prompt.go
- pkg/types/prompt.go
Based on the metadata, the receiver of the prompt event would be able to handle the prompt in a different way, if needed.
> feat: add ability to include metadata with prompts

- pkg/config/cliconfig.go
There was never a good reason to store it there anyway.
> fix: remove config file location from the config

- pkg/repos/runtimes/golang/golang.go
After downloading gptscript release, we return a full map of current environment variables and this will eventuall get saved in to done.file, which will be picked up and saved as environment variable on the next run. This is causing weird issues like https://github.com/gptscript-ai/desktop/issues/253. The original purpose of adding env variable to done.file is probably related to only append PATH, as we can see the logic here: https://github.com/gptscript-ai/gptscript/blob/56b286bd2b01fb1dd5b562f3d4c98d55147c4a20/pkg/repos/runtimes/golang/golang.go#L276. But this is not needed when downloading releases because it is always downloaded in known location.
> Fix: Do not return full env map after downloading releases

- pkg/openapi/run.go
Explicitly setting the content length instead of allowing the Go default of transfer encoding chunked.
This change only applies to the application/json request body objects using openapi.
> chore: add content length when handling json request bodies.

- pkg/openai/client.go
- pkg/openai/count.go
for gptscript-ai/desktop#283
This PR introduces three new measures to try to help the user avoid hitting the context length error:
1. Garbage collection works now. Previously, the token threshold was set too high, so we would run out of context before garbage collection would ever hit. Now, older messages will get deleted from the chat (on the LLM's side only; users can still see them) once it is needed in order to stay under the context limit.
2. If the output of a single tool output surpasses approximately 80% of the total context window, the tool output is considered too long and an error message is given to the LLM. We will design tools with the context limits in mind, but this is a safeguard to prevent just crashing and to allow the user to continue chatting with the LLM, and to …
> enhance: avoid context limit

- pkg/builtin/builtin.go
- pkg/tests/testdata/TestToolsChange/call1.golden
- pkg/tests/testdata/TestToolsChange/step1.golden
for gptscript-ai/desktop#280
This should at least help the LLM know when to _not_ call this tool.
> chore: sys.read: improve description

- pkg/builtin/builtin.go
> fix: sys.read: never read files that contain a null byte

- pkg/engine/cmd.go
Environment variables in separate slices used to point to the same underlying array. This manifested itself in parallel tool calls all having the same GPTSCRIPT_INPUT value. This PR fixes that.
This is needed for https://github.com/gptscript-ai/gptscript/issues/842
> fix: allocate new storage for env vars on each tool call

- pkg/openapi/run.go
Returning `false` here meant that the operation was not found (which is incorrect; it is found if we made it to this point in the code), and that was the error that would then be presented to the LLM, which is not what we want.
> fix: openapi revamp: fix incorrect error message when JSON args are invalid

- pkg/cli/credential.go
- pkg/credentials/store.go
- pkg/gptscript/gptscript.go
- pkg/sdkserver/credentials.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/types.go
I've tested all of these with curl and they work properly.
> feat: sdkserver: add credential routes

- pkg/sdkserver/credentials.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/server.go
The SDKServer was assuming that credential helpers were already present, which causes problems when they aren't there.
> fix: sdkserver: credentials: ensure credential helpers exist

- docs/docs/03-tools/04-credential-tools.md
- docs/docs/04-command-line-reference/gptscript.md
- docs/docs/04-command-line-reference/gptscript_credential.md
- docs/docs/04-command-line-reference/gptscript_credential_delete.md
- docs/docs/04-command-line-reference/gptscript_credential_show.md
- docs/docs/04-command-line-reference/gptscript_eval.md
- docs/docs/04-command-line-reference/gptscript_fmt.md
- docs/docs/04-command-line-reference/gptscript_getenv.md
- docs/docs/04-command-line-reference/gptscript_parse.md
- integration/cred_test.go
- integration/scripts/cred_stacked.gpt
- pkg/cli/credential.go
- pkg/cli/credential_delete.go
- pkg/cli/credential_show.go
- pkg/cli/gptscript.go
- pkg/credentials/store.go
- pkg/credentials/util.go
- pkg/gptscript/gptscript.go
- pkg/sdkserver/credentials.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/types.go
This implements the concept of "stacked" credential contexts. (Reminder: a credential context is basically just a namespace for credentials in the creds store.)
For more details on how this works, see the section that I added to the docs in this PR.
> feat: add stacked credential contexts

- examples/testkube.gpt
Adding example for testkube agent.
> Add Testkube GPT example

- pkg/gptscript/gptscript.go
This fixes a bug where `default` would always get added as one of the credential contexts for a run.
> fix: stop always adding the default cred context

- pkg/sdkserver/routes.go
- pkg/sdkserver/types.go
This is to help undo some of the damage from the breaking change.
> fix: sdkserver: rename credentialContext to credentialContexts

- main.go
- pkg/engine/cmd.go
- pkg/gptscript/gptscript.go
- **bug: load vcs support in embedded server always**
- **chore: try always running exec for "sh -c" in engine**
> bug: load vcs support in embedded server always

- pkg/credentials/noop.go
- pkg/credentials/store.go
- pkg/runner/runner.go
The stacked credentials feature was not working with credential refresh until this PR. The refreshed credential used to be stored into the highest priority context, even if it previously existed in a different context.
For example, say I had credential `cred` in context `one`, and then I do `gptscript --credential-context two,one <script>`. The script uses the `cred` credential, so it gets refreshed. GPTScript was storing the new refreshed credential in the context `two`, even though it previously existed in `one`.
This PR changes it so that refreshed credentials are always stored in the context from which they came.
> fix: modify credential refresh to support stacked contexts

- pkg/config/cliconfig.go
- pkg/credentials/store.go
- pkg/credentials/util.go
- pkg/repos/get.go
- pkg/repos/runtimes/golang/golang.go
This adds support for the new https://github.com/gptscript-ai/gptscript-credential-sqlite credential helper. It is for macOS and Linux. I will add some documentation about how to use it to its repo. By default, secrets will be unencrypted in the database, but we support using k8s EncryptionConfiguration files, which can be used to set up AES encryption, or something more sophisticated with a KMS like AWS KMS.
> feat: support sqlite credential helper

- pkg/tests/smoke/testdata/Bob/gpt-4o-2024-08-06-expected.json
- pkg/tests/smoke/testdata/BobAsShell/gpt-4o-2024-08-06-expected.json
`gpt-4o-2024-08-06` smoke tests are failing because of outdated golden files. Update the golden files to get smoke tests passing again.
Note: tested this with `-count=5` to ensure we're flake-free now
> test: regenerate gpt-4o smoke test golden files

- pkg/tests/smoke/testdata/Bob/claude-3-5-sonnet-20240620-expected.json
- pkg/tests/smoke/testdata/Bob/gpt-4o-2024-08-06-expected.json
- pkg/tests/smoke/testdata/Bob/gpt-4o-mini-2024-07-18-expected.json
- pkg/tests/smoke/testdata/Bob/mistral-large-2402-expected.json
- pkg/tests/smoke/testdata/Bob/test.gpt
- pkg/tests/smoke/testdata/BobAsShell/claude-3-5-sonnet-20240620-expected.json
- pkg/tests/smoke/testdata/BobAsShell/gpt-4o-2024-08-06-expected.json
- pkg/tests/smoke/testdata/BobAsShell/gpt-4o-mini-2024-07-18-expected.json
- pkg/tests/smoke/testdata/BobAsShell/mistral-large-2402-expected.json
- pkg/tests/smoke/testdata/BobAsShell/test.gpt
Smoke tests flake for `gpt-4o` b/c of non-determinism in how it interpreted the test case instructions (e.g. failed to interpolate a string variable consistently). This change reduces ambiguity in the tool instructions so that it produces consistent results across smoke test runs.
Note: I regenerated golden files across all models and ran the tests 10 times per model to vet this change.
> test: tweak smoke test tool bodies to standardize response text

- pkg/engine/cmd.go
- pkg/sdkserver/datasets.go
- pkg/sdkserver/routes.go
- pkg/sdkserver/workspaces.go
This change also changes the error behavior when running tools that are simply wrapped commands. Previously, all such tools would not return an error, rather an error message in hopes that the LLM would retry. However, if the tool is just a command (i.e. has no parent), then it should return an error so that the caller doesn't have to guess whether an error occurred.
> feat: add workspace API to SDK

- pkg/engine/http.go
- pkg/sdkserver/workspaces.go
This also adds support in the daemon implementation for dynamic paths, something that is needed for the workspace-provider daemon to work.
> chore: move the workspace-provider tool to a daemon

- pkg/sdkserver/datasets.go
- pkg/sdkserver/routes.go
Depends on https://github.com/gptscript-ai/datasets/pull/4
This updates the SDKServer to better handle the new changes to the dataset tools.
> chore: add Add Elements tool to dataset sdk

- pkg/credentials/error.go
- pkg/credentials/store.go
- pkg/credentials/toolstore.go
- pkg/runner/runner.go
The recent refactoring of credential helpers to be run as tools resulted in a bug where the output of the credential tool (which would become part of the error message) would have things appended to it like `:\n exit status 1`, which was messing up the detection of Not Found errors. I fixed this in this PR by implementing our own function to examine the error message. I wish I could have used the defined `const` for this from the Docker package that we depend on, but it is unexported.
> fix: credentials: check for not found errors properly

- pkg/builtin/builtin.go
- pkg/engine/engine.go
- pkg/gptscript/gptscript.go
- pkg/llm/proxy.go
- pkg/openai/client.go
- pkg/tests/tester/runner.go
If specific proxy environment variables are set, the built-in proxy will be bypassed.
> feat: allow bypassing of built-in proxy

- pkg/builtin/builtin.go
- pkg/loader/loader.go
- pkg/loader/openapi_test.go
- pkg/sdkserver/run.go
The tool loader will set the models on the tools if none is set. The way that that happens works for the CLI, but is not compatible with the SDK. This change makes the default model logic work with the SDK server.
> fix: add default model to the loader

- pkg/credentials/store.go
- pkg/engine/http.go
- **chore: allow dot in credential context**
- **chore: Add GPTSCRIPT_HTTP_ENV_PREFIX to specify http env vars to send**
> chore: Add GPTSCRIPT_HTTP_ENV_PREFIX to specify http env vars to send

- pkg/sdkserver/server.go
This tool was moved back to the gptscript-ai org.
> chore: change the dataset tool to the gptscript-ai org

- pkg/cli/credential.go
- pkg/config/cliconfig.go
- pkg/credentials/store.go
This change does two related things:
1. Allow listing of credentials in all contexts
2. When running in SDK server mode and using the file cred store, we must 
reload the credentials in the file each time. Typically, these 
credentials will be added via a tool call, which would invalidate the 
credentials held in memory.
> Fix server creds

- docs/docs/03-tools/03-openapi.md
- pkg/engine/openapi.go
- pkg/openapi/run.go
> chore: openapi: remove https restriction

- pkg/cli/gptscript.go
- pkg/gptscript/gptscript.go
- pkg/llm/registry.go
- pkg/openai/client.go
- pkg/remote/remote.go
- pkg/sdkserver/routes.go
This provides a lot more information about the models, rather than just their names.
Let me know if there is anything we want to change or redact in the output.
> enhance: sdk: list full model objects, instead of just names

- pkg/engine/engine.go
This is a safety net for instances when the LLM goes awry. There is an undocumented environment variable to change the maximum number of consecutive tool calls from the default of 10.
Issue: https://github.com/obot-platform/obot/issues/940
> enhance: add a maximum consecutive tools calls restriction

- pkg/loader/url.go
- pkg/sdkserver/routes.go
A change was made such that the cache key was removed when a tool was run with cache disabled. This change connects the cache disabled feature when running tools with the cache disabled when loading tools. That way, if a tool is loaded with cache disabled, then this newer version is used when running the tool the next time.
Related issue: https://github.com/obot-platform/obot/issues/735
> enhance: clear cache on load with disabled cache

- go.mod
- go.sum
- pkg/cli/gptscript.go
- pkg/engine/call.go
- pkg/prompt/prompt.go
- pkg/types/prompt.go
- pkg/types/prompt_test.go
Additionally, each field can now also have a description.
This change is made such that all existing tools will work. However, existing code will need to be updated to support the new types.
> enhance: add field-level sensitivity for prompts

- pkg/engine/http.go
Daemon tools can now request which environment variables it needs from the calling tool. These environment variables will be sent in the X-GPTScript-Env header.
Issue: https://github.com/obot-platform/obot/issues/1667
> feat: allow daemons to request environment variables

- pkg/credentials/factory.go
- pkg/credentials/noop.go
- pkg/credentials/overrides.go
- pkg/credentials/store.go
- pkg/sdkserver/credentials.go
- pkg/sdkserver/routes.go
> enhance: add method for recreating all credentials

- pkg/sdkserver/routes.go
Fixed a bug where run is aborted and channel will be closed twice and panic.
> Fix: fix close bug when run is aborted

- pkg/runner/runner.go
- pkg/sdkserver/run.go
for https://github.com/obot-platform/obot/issues/2367
> fix: remove unnecessary error wrapping

- pkg/credentials/credential.go
- pkg/runner/runner.go
- pkg/types/credential_test.go
- pkg/types/tool.go
If the check param changes, then the credential will be re-prompted and not used nor refreshed.
> chore: add credential checkParam field

- pkg/mcp/loader.go
- pkg/tests/runner2_test.go
This keeps us from having to duplicate this code in other places.
> chore: separate the LoadSession function in the MCP loader

- pkg/hash/sha256.go
- pkg/tests/runner2_test.go
The gob encoder is dependent on the order in which it sees types. So, even encoding a completely new type could change the "digest" of a type with the same values. This is not in the flavor or producing a digest.
This change switches to JSON, which will produce a consistent encoding.
> chore: switch from gob to JSON encoding for digests

- pkg/mcp/loader.go
If allowedTools is nil, then all tools are allowed. If allowed tools is non-nil and has length zero, then no tools are allowed.
> fix: distinguish between nil and non-nil allowed tools

- Makefile
- pkg/credentials/store.go
- pkg/credentials/toolstore.go
- pkg/credentials/toolstore_test.go
for https://github.com/obot-platform/obot/issues/3180
This PR changes the way we request a list of credentials by also including the contexts as input. The contexts are ignored by all non-database credential helpers (like Wincred and macOS Keychain), so we still filter by context after we call `GetAll`, but this allows the database credential helpers to be more efficient and only return to us the credentials that we actually need.
Once this PR is merged, I will have a PR for Obot to bump the GPTScript dependency. We might have to temporarily (or permanently, as I don't think it will do any harm) enable schema migration for the credentials table, which is currently disabled with an environment variable.
Related PR to change the credential helpers: …
> enhance: provide contexts to credential helpers when listing credentials

- pkg/openai/client.go
Anthropic LLM api doesn't like assistant message to be empty. When user abort a chat before LLM can respond, we send an empty message which will break Anthropic. This PR added a placeholder message when LLM haven't started responding.
https://github.com/obot-platform/obot/issues/3924
> Fix: add placeholder message when chat is aborted
