pkg/loader/loader.go
Proposed fix for #57.
Tested fix on Windows and AlmaLinux 9.
=> Check for http and https prefix

README.md, docs/docs/01-overview.md
Small PR to fix an annoying typo in the README 🙃
=> fix: address typo issue with readme

README.md
Pending merge of https://github.com/ScoopInstaller/Extras/pull/12827/files
Update: Merged
=> Add Scoop install to README

docs/README-USECASES.md
=> docs: Update README-USECASES.md

docs/docs/03-tools/03-openapi.md
I forgot to update this in one of my previous PRs.
=> docs: fix statement about unsupported MIME types

pkg/cli/credential.go
=> fix: remove --version from gptscript credentials

pkg/daemon/daemon.go
Fix the daemon process bug that swallow stdout.
=> Fix: fix bug that swallow stdout for daemon process

examples/nodejs-imagegen/package-lock.json, examples/nodejs-imagegen/package.json
This fixes an issue where images are not properly generating.
=> chore: update nodejs-imagegen GPTScript version

pkg/parser/parser.go, pkg/parser/parser_test.go
1. #!gptscript
2. #!/usr/bin/env gptscript
3. #!/bin/env gptscript
=> bug: check for very specific #! on line 1

pkg/loader/loader.go
This reverts commit f93bc73c545d38ea5401f03948b501d4892aef79.
=> Revert "fix: the remote bool was not being reset"

pkg/builtin/builtin.go, pkg/engine/cmd.go, pkg/gptscript/gptscript.go, pkg/monitor/display.go, pkg/monitor/fd.go, pkg/prompt/prompt.go, pkg/prompt/server.go, pkg/runner/monitor.go, pkg/runner/runner.go, pkg/sdkserver/monitor.go, pkg/server/server.go, pkg/types/prompt.go
- **enhance: ask user for OpenAI key and store it in the cred store**
- **fix lint issues**
- **chore: move prompt to always http based**
=> chore: move prompt to always http based

docs/docs/05-alternative-model-providers.md
=> Docs: Fix typo

pkg/cli/gptscript.go
=> Chore: fix UI for v0.8.2 release

pkg/cli/gptscript.go
=> chore: unpin ui version post-release

pkg/cli/gptscript.go
=> chore: bump UI for v0.8.3

pkg/gptscript/gptscript.go
for #504
This will resolve paths starting with `~/` properly.
=> fix: resolve ~ in workspace path

go.mod, go.sum, pkg/cli/gptscript.go
Make cred overrides work when using the TUI.
=> enhance: pass cred overrides to tui

pkg/credentials/credential.go
=> chore: strip leading and trailing whitespace characters from credential values

pkg/cache/cache.go
=> fix: expand tilde and relative paths to be absolute for cache-dir

pkg/sdkserver/datasets.go
depends on https://github.com/otto8-ai/datasets/pull/9
=> chore: sdkserver: use the Get Element SDK tool

pkg/config/cliconfig.go, pkg/credentials/util.go
depends on https://github.com/gptscript-ai/gptscript-credential-sqlite/pull/7
=> chore: add postgres credential helper

pkg/sdkserver/datasets.go, pkg/sdkserver/routes.go
depends on https://github.com/otto8-ai/datasets/pull/11
=> chore: sdkserver: update dataset methods for the rewrite

pkg/sdkserver/workspaces.go
The workspace-provider daemon expects fromWorkspaceIDs instead of workspace_ids.
=> fix: send the correct payload when creating workspaces from workspaces

docs/docs/03-tools/02-authoring.md, docs/docusaurus.config.js
=> Chore: Drop tools.gptscript.ai
